# This workflow:
#   - lints the chart, runs tests and verifies documentation is up to date
# Additionally if the event isn't a pull-request (and hence a merge/push to main):
#   - sync README to gh-pages branch
#   - release a new chart version if the version isn't already released
name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:

# Cancel previous PR builds.
concurrency:
  # Cancel all workflow runs except latest within a concurrency group. This is achieved by defining a concurrency group for the PR.
  # Non-PR builds have singleton concurrency groups.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
      - name: Lint charts
        run: ct lint --charts=charts/trino --validate-maintainers=false

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
      - name: Install charts
        run: ct install --charts=charts/trino
